### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by kitze** [kitze/create-react-app#1]
The jest tests are currently failing if Babel stage-0 or decorators are used.

**Comment by karbica** [comment]
Also worth mentioning jest tests fail if a file imports `.scss`, `.styl`, or `.less` style sheets. Besides that, this project is gold.

**Comment by lukaszgolder** [comment]
@karbica it was fixed by my PR but isn't published yet

**Comment by kitze** [comment]
@lukaszgolder is babel-stage-0 also fixed, or just styles?

**Comment by lukaszgolder** [comment]
@kitze No, I was only referring to error with stylesheets. But I am using some stage-3 features in my project and didn`t come into any error yet.
