### ISSUE TITLE
REACT_APP_SASS does not generate CSS file

### ISSUE THREAD

**Issue by jbach** [kitze/create-react-app#10]
When `REACT_APP_SASS=true`, the CSS is embedded in the JS file rather than output as a separate CSS file.  I guess `ExtractTextPlugin.extract` is missing for the Sass loader?

**Comment by kitze** [comment]
This should be only happening in development mode, in production mode when using ```npm run build``` the compiled css should be in an extra file because ```ExtractTextPlugin.extract``` is configured.

**Comment by jbach** [comment]
I’ve added a reduced testcase to https://github.com/jbach/custom-react-scripts-sass. Try running `npm run build`, the css will not be extracted. Am I doing something wrong? Maybe I’m confused, but looking at [config/customizers.js](blob/master/packages/react-scripts/config/customizers.js#L19), I don’t see `ExtractTextPlugin.extract`. 

When I manually change the sass-loader in `config/customizers.js`to
```JavaScript
'SASS': {
    toArray: 'loaders',
    get: function () {
      return {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract('style', "css!postcss!sass")
      }
    }
  }
```
a separate CSS file is built.

**Comment by kitze** [comment]
Just released 0.0.14 with [a better fix](https://github.com/kitze/create-react-app/commit/fd7c7b46b70400fc88f33949df5aa29ea1bf9f43) for this. Now each customizer has a getDev and getProd functions. Should be ok now.

**Comment by jbach** [comment]
Thank you for the fix, but can you confirm 0.0.14 is installable via npm? Installation via `npm i custom-react-scripts` fails for me with Node 6.6.0 / npm 3.10.3. [See my full npm-debug.log](https://gist.github.com/jbach/b8701a5c5f6b4357035eada72ee66066#file-npm-debug-log-L9973)

```
npm ERR! Path must be a string. Received undefined
```

**Comment by kitze** [comment]
Yes. I got the same error with Node v6.6.0. I also see other people [have this issue]with different npm packages (https://github.com/webpack/webpack/issues/2463) but I have no idea why. 

Installing the scripts with Node v.6.2.0 worked completely fine for me. Please try it and let me know.

**Comment by jbach** [comment]
I’ll close this issue. The nonrelated install bug is described in https://github.com/kitze/create-react-app/issues/13
