### ISSUE TITLE
Can't compile SASS

### ISSUE THREAD

**Issue by stereobooster** [kitze/create-react-app#11]
### Description

This is probably pretty lame and obvious thing that I'm missing, but still can't figure out.

### Expected behavior

I created app with custom scripts, copied `App.scss` from this repo, added `REACT_APP_SASS=true` to env. Run `npm start` and got error:

```
Failed to compile.

Error in ./src/App.scss
Module parse failed: /Users/.../my/my-app — scripts-version/src/App.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
 @ ./src/App.js 18:0-21
```

### Actual behavior

It should compile scss files.

### Environment
```
➜ npm ls react-scripts
my_app@0.0.1 /Users/x/my/my-app — scripts-version
└── react-scripts@0.6.1
➜ node -v
v6.1.0
➜ npm -v
3.8.6
```
1. Operating system: Mac OS X
2. Browser and version: Chrome

### Reproducible Demo
https://github.com/stereobooster/test-custom-react-scripts

**Comment by kitze** [comment]
In your package.json you're using the original react-scripts. You should install custom-react-scripts instead.

### Fix for this project
Just remove ```react-scripts```  from here:
```
"devDependencies": {
    "react-scripts": "0.6.1"
  },
```
And ```npm install --save-dev custom-react-scripts```.

### Advice for future projects
When you generate your projects with "create-react-app" in the future, please specify the version of the scripts like this: ```create-react-app my-sample-app --scripts-version custom-react-scripts```

This should solve  your issue.

**Comment by stereobooster** [comment]
Yes that fixed problem. Thanks a lot. Not sure how I get into it. I used `--scripts-version custom-react-scripts`

PS. I thought that it is possible to add obvious comment to issue report template, like if `npm ls react-scripts` output looks like 

```
my_app@0.0.1 /Users/x/my/my-app — scripts-version
└── react-scripts@x.x.x
```

you need to switch to `custom-react-scripts`...

After I switched:

```
npm ls react-scripts
test-custom-react-scripts@0.0.1 /Users/x/my/test-custom-react-scripts
└── (empty)

npm ERR! code 1
```
