### ISSUE TITLE
Road map and plans for Flowtype support?

### ISSUE THREAD

**Issue by stereobooster** [kitze/create-react-app#12]
Hi. This is a great project. Thanks for creating it.

Do you have roadmap? And do you have plans to add FlowType support?

Want to replace [propTypes with Flow](http://blog.rstankov.com/flow-as-replacement-for-proptype/).

Also looking for something similar to [typed-css-modules](https://github.com/Quramy/typed-css-modules) for Flow and CSSModules.

**Comment by kitze** [comment]
Flow [already works](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-flow).

I've never used typed-css-modules but from what i read in the readme, it's not integrated with webpack or babel in any way, right? So it should work too.

**Comment by kitze** [comment]
Here's a sample .flowconfig file:

```
[ignore]
.*/node_modules/fbjs/.*
.*/node_modules/react-event-listener/.*

[options]
module.system.node.resolve_dirname=node_modules
module.system.node.resolve_dirname=src
module.name_mapper.extension='scss' -> '<PROJECT_ROOT>/file-stub.js'
module.name_mapper.extension='css' -> '<PROJECT_ROOT>/file-stub.js'
module.name_mapper.extension='less' -> '<PROJECT_ROOT>/file-stub.js'
module.name_mapper.extension='png' -> '<PROJECT_ROOT>/file-stub.js'
module.name_mapper.extension='jpg' -> '<PROJECT_ROOT>/file-stub.js'
```

It will work with absolute imports and it will ignore scss, less, css, png, jpg files.

You also need to have a ```file-stub.js``` file in the root of the project. The content of that file is:```declare export default void;```

Please let me know if this works for you.

**Comment by kitze** [comment]
Final config is [here](https://gist.github.com/kitze/63ac677fbd70bda72d10756e6e0d3d87). It supports every feature that ``custom-react-scripts``` supports. I will add it to the readme later.

**Comment by stereobooster** [comment]
Just an idea add `generate_flow_config` command which wlil add this config to repo (like eject).

**Comment by kitze** [comment]
@stereobooster yeah I thought about it too but every line of that .flowconfig 👆 depends if a feature is turned on/off in .env. So if decorator support is toggled in .env, I should check if ```esproposal.decorators=ignore``` is in .flowconfig etc. etc.
