### ISSUE TITLE
Support CSSModules for SASS.

### ISSUE THREAD

**Issue by stereobooster** [kitze/create-react-app#21]
I need this feature to have out of the box integration with react-toolbox. See https://github.com/react-toolbox/react-toolbox-example/pull/35

The question is if we have: 

```
REACT_APP_SASS=true
REACT_APP_CSS_MODULES=true
```

Does it always mean we want CSSModules for SASS? I suppose yes

**Comment by claylevering** [comment]
+1 to this, I just ran into this and was thinking about possibly contributing code but I'm not the world's best CSS Modules expert... perhaps I'll look at it tonight.

**Comment by stereobooster** [comment]
Solution is simple, question is how to integrate it

```json
  'SASS': {
    toArray: 'loaders',
    getDev: function () {
      return {
        test: /(\.scss|\.sass)$/,
        loader: "style!css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss"
      }
    },
    getProd: function () {
      return {
        test: /(\.scss|\.sass)$/,
        loader: ExtractTextPlugin.extract('style', 'css?modules&-autoprefixer&importLoaders=1!postcss')
      }
    }
  },
```

**Comment by claylevering** [comment]
@stereobooster - Does that seem to work?

**Comment by stereobooster** [comment]
Created PR so closing issue. https://github.com/kitze/create-react-app/pull/23
