### ISSUE TITLE
Use CSS modules and global css together?

### ISSUE THREAD

**Issue by wong2** [kitze/create-react-app#29]
Hi, with the original `create-react-app`, I can build global css files into my bundle js like this: 
`import 'font-awesome/css/font-awesome.css`
Then I switched to `custom-react-scripts` since I want to use css modules inside my react components, it works great. However, it also breaks the global css import as showed above.
Is there anyway I can use both of them? thanks

**Comment by billel-boudchicha** [comment]
same issue here , with global and local css .
using bootstrap for exemple with some local css, i add (.global.css) to the bootstrap file, and  only (.css) to the local style , and eject my project and add the following to dev.config
`{
        test: /^((?!\.global).)*css$/,
        loader: customConfig.values.CSS_MODULES ? customConfig.values.CSS_MODULES.dev : 'style!css?importLoaders=1!postcss'
      },
      {
        test: /\.global.css$/,
        loader: 'style!css?importLoaders=1!postcss'
      },`
works great in dev mode but not working in production .

**Comment by dvkndn** [comment]
Hey guys, this issue is resolved in CSS Modules repo. Please see: https://github.com/css-modules/css-modules/pull/65#issuecomment-248280248

I'm working to push it to Readme FAQ 😄

**Comment by wong2** [comment]
@dvkndn great!

**Comment by kitze** [comment]
@dvkndn awesome!

**Comment by wong2** [comment]
a side note to @dvkndn 's solution:
you need to add this line to the top of your `index.js` file to avoid a eslint error:
`/* eslint import/no-webpack-loader-syntax: "off" */`
