### ISSUE TITLE
Q: Is it possible to use "custom-react-scripts" on an existing app created by create-react-app?

### ISSUE THREAD

**Issue by topvis** [kitze/create-react-app#30]
Is it possible to use "custom-react-scripts" on an existing app created by create-react-app? Or do I have to use `create-react-app my-app --scripts-version custom-react-scripts` to scaffold a new app?
By the way I found your lib by reading your Medium article "Configure create-react-app without ejecting". Very nice article :+1:  Thanks.

**Comment by kitze** [comment]
Yes it's possible. You just need to remove the ```react-scripts``` dependency from package.json and install this package instead. That's it.

Btw: thanks! 🙌

**Comment by dwelch2344** [comment]
For those of us who are lazy: 
```yarn remove react-scripts && yarn add custom-react-scripts``` 

:)

**Comment by TechyTimo** [comment]
I failed to move my project...
I had a create-react-app already working then I did the following:

`npm remove react-scripts --save-dev
npm install custom-react-scripts --save-dev`

**1. It didn't generate any .env file.**

Also I changed my package.json file to reference "custom-react-scripts" as opposed to "react-scripts"

**2. "npm start" failed with "custom-react-scripts: command not found"**

{
  "name": "project",
  "version": "1.0.0",
  "private": true,
  "homepage": ".",
  "devDependencies": {
    "custom-react-scripts": "^0.1.4",
    "gulp": "^3.9.1"
  },
  "dependencies": {
    "chart.js": "2.5.0",
    "mobx": "^3.2.2",
    "mobx-react": "^4.2.2",
    "react": "15.6.1",
    "react-addons-css-transition-group": "15.5.0",
    "react-addons-transition-group": "15.5.0",
    "react-avatar-cropper": "^0.1.3",
    "react-bootstrap": "^0.31.2",
    "react-breadcrumbs": "1.6.6",
    "react-chartjs-2": "2.0.5",
    "react-dom": "15.6.1",
    "react-ladda": "5.0.6",
    "react-router": "3.0.3",
    "react-select": "1.0.0-rc.5",
    "react-text-mask": "4.1.0",
    "reactstrap": "4.5.0"
  },
  "scripts": {
    "start": "custom-react-scripts start",
    "build": "custom-react-scripts build",
    "test": "custom-react-scripts test --env=jsdom",
    "eject": "custom-react-scripts eject"
  }
}

**Comment by TechyTimo** [comment]
Sorry... I actually got it solved by just using the command react-scripts instead of custom-react-scripts for the scripts part of my package json
