### ISSUE TITLE
Add the github repo to the npm package

### ISSUE THREAD

**Issue by lewisdiamond** [kitze/create-react-app#34]
This would add a link to this repo from the npmjs.com page and make it easier to get here. Otherwise we need to search for your username.

**Comment by kitze** [comment]
Hmm, there is already a link in the package.json, and you can see that [it appears on the npm page](http://jmp.sh/YI4GQoU). Anything else that I should add?

**Comment by lewisdiamond** [comment]
I mean for this field.

https://docs.npmjs.com/files/package.json#repository

![screenshot from 2016-12-12 13-20-20](https://cloud.githubusercontent.com/assets/1375600/21111126/11a9295a-c06e-11e6-856d-801f7d7d25bb.png)

**Comment by kitze** [comment]
Ah thanks.
