### ISSUE TITLE
Upgrade to `react-scripts` 0.8.1

### ISSUE THREAD

**Issue by joshwcomeau** [kitze/create-react-app#39]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Can you reproduce the problem with latest npm?

Yes

### Description

`react-scripts` [introduced a bug](https://github.com/facebookincubator/create-react-app/issues/1145) in which Jest will auto-mock files in different directories.

I am assuming the latest version of `custom-react-scripts` relies on `react-scripts` 0.8.0, because I'm experiencing this issue with it.

Upgrading to 0.8.1 should fix it :)

### Expected behavior

The functions should be imported properly, so that they can be genuinely tested.

### Actual behavior

The functions imported are replaced with a string that reads 'test-file-stub`

**Comment by kitze** [comment]
Done! 🙌
