### ISSUE TITLE
How do you update react-app folder without overwriting your changes?

### ISSUE THREAD

**Issue by aligajani** [kitze/create-react-app#44]
How would I do it without asking you for example? I want to have latest versions of both.

Latest `react-scripts` is 0.8.4

Also please outline all the files that you have modified/added for giving us this custom setup.

Of course, it is for our knowledge. Thank you very much @kitze

**Comment by kitze** [comment]
You would have to wait until I update this package to the latest react-scripts, sorry.

I will give an outline of everything modified soon.
