### ISSUE TITLE
Dumb Question: What else is needed to support SASS?

### ISSUE THREAD

**Issue by mwadden** [kitze/create-react-app#56]
Other than adding REACT_APP_SASS=true to the .env file, what other steps are required to get SASS working? Here's what I've tried:

1. Renaming App.css to App.scss and changed the import to match
2. Installed various babel loader modules: sass-loader, style-loader, css-loader, postcss-loader, node-sass

I feel like I'm missing something obvious here...

Thx

**Comment by esausilva** [comment]
I didn't have to install anything additional, just setting `REACT_APP_SASS=true` works...and obviously having the actual SASS file

**Comment by mwadden** [comment]
So it turns out something was just wonky with my install. I created a new project and now it's working.
