### ISSUE TITLE
Only while starting a new project ?

### ISSUE THREAD

**Issue by DataMkP** [kitze/create-react-app#9]
Thanks for the work (I need Sass).

I wonder if it is possible to update a project based on CRA with your custom script. I understand that we can use it only while creating a new app.

**Comment by martinschayna** [comment]
IMHO just replace `react-scripts` with `custom-react-scripts` in the `package.json` with appropriate version and add `.env` file?

**Comment by kitze** [comment]
@martinschayna is right. Just remove react-scripts from your dependencies, and install ```custom-react-scripts```. The name in the npm scripts should stay ```react-scripts``` though.

I also explained it in [this issue](https://github.com/kitze/create-react-app/issues/11#issuecomment-250968102).

**Comment by DataMkP** [comment]
Thanks for the answers
